# Contains secrets, like API keys.
# Don't forget to rename this file to secrets.yml, and do not add secrets.yml to git!
# This file can be used by various initializer to load API keys

facebook:
  app_id: 'Your facebook app ID here'
  app_secret: 'Your facebook app secret here'

  # If you are using different facebook apps for the development and staging/production environments, enter the development API keys below
  development:
    app_id: 'Your facebook app ID here'
    app_secret: 'Your facebook app secret here'

